### PR TITLE
Updated documentation about run docker example (#20)

### PR DESCRIPTION
**Pull request by jwackito**
Solve issue #20

### CODE REVIEW

**Comment by cirojas** [comment]
thank you for your comments, I will merge the pull request.

By the way, although we have not updated the repository in a while, we are in active development, but we are waiting to finish some important features (and test and document them) before publishing the new version. If you are interested in using MillenniumDB let me know and I can publish our current version and explain how to use it.

**Comment by jwackito** [comment]
I would love to. Let me know.

**Comment by cirojas** [comment]
@jwackito I have uploaded it to the `preview` branch.

Many things have changed compared to the main branch, the most important ones are:
- Now we support some SPARQL updates (we implement a variation of MVCC to enable one write operation at the same time of many reads)
- We have a new web browser interface
- Default server port changed
- Some bugs with SPARQL expressions and aggregations were fixed
- Databases created with the previous version are not compatible with the new version, you have to import it again.

The instructions for usage are similar but different, make sure to follow the [new instructions](https://github.com/MillenniumDB/MillenniumDB/blob/preview/README.md).

**Comment by jwackito** [comment]
That's great! I will take a look during the week and let you know! Thanks!

**Pull request merged**
